name: WU Scheduler minuto 17

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

permissions:
  contents: write

jobs:
  aggiorna-dati:
    uses: ./.github/workflows/update-wunderground.yml
    secrets: inherit
